In [260]:
import sys
import torch
import numpy as np

In [261]:
sys.path.append('/envs')
sys.path.append('/models')
import envs.viper as vpr
import models.models as models
import models.dqn as dqn

In [262]:
import importlib
importlib.reload(vpr); importlib.reload(models); importlib.reload(dqn)

<module 'models.dqn' from 'h:\\Coding Projects\\Python Projects\\Deep-XIV-Rotation\\models\\dqn.py'>

In [263]:
viper_env = vpr.Viper()

b123


In [264]:
viper_env.get_max_actions()

11

In [265]:
viper_env.get_state_shape()

7

In [266]:
state = viper_env.state()
state[None, :]

tensor([[ 0.0000,  2.5000, 10.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [267]:
state.unsqueeze(0)

tensor([[ 0.0000,  2.5000, 10.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [268]:
agent = dqn.DQN(viper_env)

Layer (type:depth-idx)                   Output Shape              Param #
DenseNet                                 [8, 11]                   --
├─Linear: 1-1                            [8, 2048]                 16,384
├─Linear: 1-2                            [8, 11]                   22,539
Total params: 38,923
Trainable params: 38,923
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.31
Input size (MB): 0.00
Forward/backward pass size (MB): 0.13
Params size (MB): 0.16
Estimated Total Size (MB): 0.29


In [269]:
torch.device('cpu')

device(type='cpu')

In [270]:
inputs = torch.rand(5, viper_env.get_state_shape())
print(inputs)
preds = agent.get_action(inputs)
print(preds)

tensor([[0.7685, 0.9610, 0.8398, 0.1670, 0.5683, 0.0702, 0.0921],
        [0.6926, 0.5386, 0.3597, 0.8761, 0.2163, 0.3135, 0.2442],
        [0.6679, 0.2986, 0.2411, 0.0964, 0.4470, 0.1150, 0.8998],
        [0.7751, 0.4948, 0.6451, 0.5312, 0.2863, 0.9579, 0.2592],
        [0.4172, 0.3618, 0.5731, 0.6165, 0.1385, 0.4234, 0.7296]])
tensor([8, 8, 8, 8, 8], dtype=torch.int32)


In [271]:
print(viper_env.step(1))
viper_env.state()

Taking action steel_fangs
193.0


tensor([ 0.7000,  2.5000,  0.7000,  1.0000, 59.3000,  0.0000,  0.0000])

In [272]:
print(viper_env.step(0))
viper_env.state()

Taking action nothing
-1.0


tensor([ 0.8000,  2.5000,  0.8000,  1.0000, 59.2000,  0.0000,  0.0000])

In [273]:
print(viper_env.step(3))
viper_env.state()

Taking action hunters_sting
306.0


tensor([ 3.2000,  2.5000,  0.7000,  2.0000, 56.8000,  0.0000, 40.0000])

In [274]:
np.random.uniform(0.95, 1.05)

0.9579636816295194