In [207]:
import sys
import torch

In [208]:
sys.path.append('/envs')
sys.path.append('/models')
import envs.viper as vpr
import models.models as models
import models.dqn as dqn

In [209]:
import importlib
importlib.reload(vpr); importlib.reload(models); importlib.reload(dqn)

<module 'models.dqn' from 'h:\\Coding Projects\\Python Projects\\Deep-XIV-Rotation\\models\\dqn.py'>

In [210]:
viper_env = vpr.Viper()

b123


In [211]:
viper_env.get_max_actions()

11

In [212]:
viper_env.get_state_shape()

torch.Size([7])

In [213]:
state = viper_env.state()
state[None, :]

tensor([[ 0.0000,  2.5000, 10.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [214]:
state.unsqueeze(0)

tensor([[ 0.0000,  2.5000, 10.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [215]:
agent = dqn.DQN(viper_env)

Layer (type:depth-idx)                   Output Shape              Param #
DenseNet                                 [8, 11]                   --
├─Linear: 1-1                            [8, 2048]                 16,384
├─Linear: 1-2                            [8, 11]                   22,539
Total params: 38,923
Trainable params: 38,923
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.31
Input size (MB): 0.00
Forward/backward pass size (MB): 0.13
Params size (MB): 0.16
Estimated Total Size (MB): 0.29


In [216]:
torch.device('cpu')

device(type='cpu')

In [217]:
inputs = torch.rand(5, viper_env.get_state_shape()[0])
print(inputs)
preds = agent.get_action(inputs)
print(preds)

tensor([[3.7735e-01, 6.3062e-01, 4.3049e-01, 2.0442e-01, 8.3105e-01, 3.8757e-01,
         8.7209e-02],
        [1.2344e-01, 3.3836e-01, 4.6843e-04, 8.4835e-01, 1.8654e-01, 8.6744e-01,
         3.1502e-01],
        [7.0367e-01, 8.8972e-01, 9.9454e-01, 6.9192e-02, 7.5608e-02, 4.9730e-01,
         2.9389e-02],
        [2.7790e-01, 1.7241e-01, 6.9930e-01, 9.4985e-01, 7.4527e-02, 5.7145e-01,
         7.4276e-01],
        [6.7581e-02, 1.5096e-01, 8.9939e-01, 4.3687e-01, 2.2044e-01, 4.0554e-01,
         2.9278e-01]])
tensor([3, 1, 9, 5, 5], dtype=torch.int32)


In [218]:
print(viper_env.step(1))
viper_env.state()

Taking action steel_fangs
193.0


tensor([ 0.7000,  2.5000,  0.7000,  1.0000, 59.3000,  0.0000,  0.0000])

In [219]:
print(viper_env.step(0))
viper_env.state()

Taking action nothing
-1.0


tensor([ 0.8000,  2.5000,  0.8000,  1.0000, 59.2000,  0.0000,  0.0000])

In [220]:
print(viper_env.step(3))
viper_env.state()

Taking action hunters_sting
306.0


tensor([ 3.2000,  2.5000,  0.7000,  2.0000, 56.8000,  0.0000, 40.0000])