In [1]:
import sys
import torch
import numpy as np

In [2]:
sys.path.append('/envs')
sys.path.append('/models')
import envs.viper as vpr
import models.models as models
import models.dqn as dqn

In [3]:
import importlib
importlib.reload(vpr); importlib.reload(models); importlib.reload(dqn)

<module 'models.dqn' from 'h:\\Coding Projects\\Python Projects\\Deep-XIV-Rotation\\models\\dqn.py'>

In [4]:
viper_env = vpr.Viper(_sks = 798)

b123


In [5]:
torch.cuda.empty_cache()

In [6]:
#state = viper_env.state()
#state[None, :]

In [7]:
#state.unsqueeze(0)

In [8]:
agent = dqn.DQN(viper_env, max_history=512)

Created a model with 12 features and 10 actions.
Model loaded onto cuda:0.
Layer (type:depth-idx)                   Output Shape              Param #
DenseNet                                 [512, 10]                 --
├─Sequential: 1-1                        [512, 10]                 --
│    └─Linear: 2-1                       [512, 4096]               53,248
│    └─ReLU: 2-2                         [512, 4096]               --
│    └─Linear: 2-3                       [512, 2048]               8,390,656
│    └─BatchNorm1d: 2-4                  [512, 2048]               4,096
│    └─ReLU: 2-5                         [512, 2048]               --
│    └─Dropout: 2-6                      [512, 2048]               --
│    └─Linear: 2-7                       [512, 2048]               4,196,352
│    └─ReLU: 2-8                         [512, 2048]               --
│    └─Linear: 2-9                       [512, 1024]               2,098,176
│    └─ReLU: 2-10                        [512, 1024]

In [9]:
viper_env.compute_gcd(2.5, 798, 15)

2.08

In [10]:
action_sequence=[1, 3, 6, 9, 0, 2, 5, 0, 0]

In [11]:
for action in action_sequence:
    print(viper_env.step(action, _verbose=True))
    print(viper_env.state())

Took action: 1-reaving_fangs @ 0.000
(2.6, 200, 192.78)
tensor([ 2.4500,  0.7000,  1.0000,  0.0000, 59.3000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000])
Took action: 3-swiftskins_sting @ 2.450
(1.1, 300, 310.28)
tensor([ 2.4500,  0.7000,  3.0000,  0.0000, 56.8500,  0.0000, 39.3000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000])
Took action: 6-hindsting_strike @ 4.900
(3.1, 400, 407.15)
tensor([ 2.0800,  0.7000,  0.0000,  0.0000, 54.4000,  0.0000, 36.8500, 59.3000,
         0.0000,  0.0000,  0.0000,  1.0000])
Took action: 9-death_rattle @ 5.600
(4.2, 280, 287.24)
tensor([ 2.0800,  1.4000,  0.0000,  0.0000, 53.7000,  0.0000, 36.1500, 58.6000,
         0.0000,  0.0000,  0.0000,  0.0000])
Took action: 0-steel_fangs @ 6.980
(3.2399999999999998, 300, 305.49)
tensor([ 2.0800,  0.7000,  1.0000, 59.3000,  0.0000,  0.0000, 34.7700, 57.2200,
         0.0000,  0.0000,  0.0000,  0.0000])
Took action: 2-hunters_sting @ 9.060
(1.8399999999999999, 300, 293.78)
tensor

In [12]:
agent.env.reset_env()
print(agent.env.state())
print(agent.env.valid_actions())
print([np.random.choice(agent.env.valid_actions()[1])])

tensor([ 2.4500, 10.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000])
([True, True, False, False, False, False, False, False, False, False], [0, 1])
[0]


In [13]:
agent.get_action(agent.env.state(), e=1)[0]

tensor(7, dtype=torch.int32)

In [19]:
agent.train(gamma=0.65, num_epochs=200, session_limit=400,
            starting_e=0.8, min_e=0.45, e_decay_factor=0.98)

TypeError: DQN.train() got an unexpected keyword argument 'starting_e'

In [15]:
agent.load_checkpoint('./checkpoints/_dense_best.pth')

h:\Coding Projects\Python Projects\Deep-XIV-Rotation\models\dqn.py:208: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(path)


In [16]:
agent.test(num_steps=30)

tensor([ 2.4500, 10.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000])
Took action: 1-reaving_fangs @ 0.000
(2.6, 200, 206.06)
Took action: 3-swiftskins_sting @ 2.450
(1.1, 300, 291.95)
Took action: 7-hindsbane_fang @ 4.900
(3.1, 400, 388.22)
Took action: 0-steel_fangs @ 6.980
(1.8399999999999999, 300, 314.92)
Took action: 2-hunters_sting @ 9.060
(1.8399999999999999, 300, 304.86)
Took action: 4-flanksting_strike @ 11.140
(6.840000000000001, 550.0, 533.93)
Took action: 1-reaving_fangs @ 13.220
(2.44, 330.0, 337.66)
Took action: 3-swiftskins_sting @ 15.300
(2.44, 330.0, 314.15)
Took action: 7-hindsbane_fang @ 17.380
(4.6400000000000015, 440.00000000000006, 437.44)
Took action: 0-steel_fangs @ 19.460
(2.44, 330.0, 320.71)
Took action: 2-hunters_sting @ 21.540
(2.44, 330.0, 323.37)
Took action: 4-flanksting_strike @ 23.620
(6.840000000000001, 550.0, 535.75)
Took action: 7-hindsbane_fang @ 24.320
(-0.8, 0.0, 0.0)
Took action: 7-hindsbane

In [17]:
agent.predict(agent.env.state())

tensor([[ 0.3475,  0.3518,  0.4629,  0.3313,  0.3709,  0.2304,  0.2890,  0.1358,
         -0.1007,  0.0504]], device='cuda:0')

In [18]:
agent.env.state()

tensor([ 2.0800,  0.7000,  1.0000, 59.3000,  0.0000, 28.9000, 35.1400,  0.0000,
        57.2200,  0.0000, 50.9800,  0.0000])

In [31]:
itr = 0
for _ in range(35):
    print((np.cos(itr)+1)/2, itr)
    itr+=np.pi/10
    if itr > np.pi * 2:
        itr -= np.pi * 2

1.0 0
0.9755282581475768 0.3141592653589793
0.9045084971874737 0.6283185307179586
0.7938926261462366 0.9424777960769379
0.6545084971874737 1.2566370614359172
0.5 1.5707963267948966
0.34549150281252633 1.8849555921538759
0.2061073738537635 2.199114857512855
0.09549150281252633 2.5132741228718345
0.024471741852423234 2.827433388230814
0.0 3.141592653589793
0.02447174185242318 3.4557519189487724
0.09549150281252627 3.7699111843077517
0.20610737385376338 4.084070449666731
0.3454915028125262 4.39822971502571
0.4999999999999999 4.71238898038469
0.6545084971874736 5.026548245743669
0.7938926261462365 5.340707511102648
0.9045084971874737 5.654866776461628
0.9755282581475768 5.969026041820607
1.0 6.283185307179586
0.9755282581475768 0.3141592653589793
0.9045084971874737 0.6283185307179586
0.7938926261462366 0.9424777960769379
0.6545084971874737 1.2566370614359172
0.5 1.5707963267948966
0.34549150281252633 1.8849555921538759
0.2061073738537635 2.199114857512855
0.09549150281252633 2.513274122871